### ISSUE TITLE
Protections des données et RGPD

### ISSUE THREAD

**Issue by Chalchiuhtecolotl** [lucasmrdt/mon-attestation-covid#1]
Depuis plusieurs jours le [site du gouvernement](https://media.interieur.gouv.fr/deplacement-covid-19/) propose un système similaire pour sauvegarder les données.

J’ai pu apercevoir l’utilisation du service Google Analytics dans votre code. L’objectif de l’application du gouvernement est de simplement générer un PDF, enregistrer des données confidentielles dans le navigateur et ne dispose d’aucun service de traceurs. Est-ce judicieux d’utiliser ce genre de service sur une application qui sauvegarde des données confidentielles et génère simplement des attestations ? Il n’y a aucun bandeau pour signaler la présence de Google Analytics sur votre site (par rapport aux recommandations de la CNIL).

![Capture d’écran provenant de la dernière version du site du gouvernement](https://i.imgur.com/N4eON7G.png)

**Comment by lucasmrdt** [comment]
Bonjour,

J'ai en effet pu constater de récent changement du côté du service web et application du gouvernement. À la date de création de ce projet la possibilité de sauvegarde des données n'était pas présente sur ces services.

Aujourd'hui, le gouvernement a fait le nécessaire sur ces derniers afin de faciliter la création d'une attestation, ce qui rend ce projet moins utile qu'auparavant.

Pour le critère de l'analytics vous aurez sûrement pu constater qu'il ne génère qu'un unique événement afin de comptabiliser le nombre de vues générées sur le site. Au vue de sa faible utilité ainsi que de la présence d'informations sensibles sauvegardées localement, je pense le supprimer au plus vite.

**Comment by lucasmrdt** [comment]
Bonjour,

En effet le site officiel du gouvernement a ajouté cette fonctionnalité le 3 novembre 2020 cependant vous pourrez rapidement vérifier que mon projet a été publié le 1 novembre 2020. Il est vrai qu'au vu de l'ajout de cette fonctionnalité sur le site officiel, mon service proposé perd un peu de son intérêt même s'il permet toujours la création d'une attestation  en moins d'interactions (permettant donc toujours un gain de temps non négligable). Les utilisateurs sont tout à fait libres d'utiliser l'un des deux services.

Du point de vue d'analytics vous avez raison. L'intégration de ce dernier est uniquement utilisé afin de comptabiliser le nombre de visites du site à titre indicatif. J'ai donc pris soin de mettre en conformité ce dernier avec la RGPD. L'implémentation de Google Analytics sur le site ne présente pas de risque au niveau de la sécurité des données personnelles des utilisateurs (en effet aucune donnée personnelle/identifiable n'est envoyée à des services tiers).
